# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8aa28822bb666de7432fbe0c3f1e64d8"
name = "wishlink-pixel-integration"
handle = "wishlink-pixel-integration"
application_url = "https://q-couple-suzuki-leo.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "atg-plugin-test-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,read_customers,read_orders,read_products,write_orders,write_pixels"

[auth]
redirect_urls = [
  "https://q-couple-suzuki-leo.trycloudflare.com/auth/callback",
  "https://q-couple-suzuki-leo.trycloudflare.com/auth/shopify/callback",
  "https://q-couple-suzuki-leo.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
