name = "Wishlink-Pixel"
type = "web_pixel_extension"


runtime_context = "strict"

[settings]
type = "object"

[customer_privacy]
analytics = false
marketing = false
preferences = false
sale_of_data = "enabled"

[settings.fields.accountID]
name = "Account ID"
description = "Account ID"
type = "single_line_text_field"
validations =  [
  { name = "min", value = "1" }
]
